// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGamesSite.Data;

#nullable disable

namespace VideoGamesSite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205232543_AddTopGames")]
    partial class AddTopGames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideoGamesSite.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("HoursPlayed")
                        .HasColumnType("int");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Action RPG",
                            HoursPlayed = 120,
                            PlatformId = 1,
                            ReleaseYear = 2022,
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Roguelike",
                            HoursPlayed = 40,
                            PlatformId = 4,
                            ReleaseYear = 2020,
                            Title = "Hades"
                        });
                });

            modelBuilder.Entity("VideoGamesSite.Models.NowPlayingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Focus")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("NowPlayingItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Focus = "Beating story with girlfiend",
                            Platform = "Xbox",
                            Progress = 20,
                            Title = "Halo CE"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Focus = "Beating the bosses",
                            Platform = "PC",
                            Progress = 0,
                            Title = "Ark Survival Ascended"
                        });
                });

            modelBuilder.Entity("VideoGamesSite.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PC"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PS5"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Xbox"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Switch"
                        });
                });

            modelBuilder.Entity("VideoGamesSite.Models.TopGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("TopGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Rank = 1,
                            Tag = "FPS",
                            Title = "Halo: Reach"
                        },
                        new
                        {
                            Id = 2,
                            Rank = 2,
                            Tag = "FPS",
                            Title = "Halo 3"
                        },
                        new
                        {
                            Id = 3,
                            Rank = 3,
                            Tag = "TPS",
                            Title = "Gears of War 2"
                        },
                        new
                        {
                            Id = 4,
                            Rank = 4,
                            Tag = "Looter Shooter",
                            Title = "Borderlands 2"
                        },
                        new
                        {
                            Id = 5,
                            Rank = 5,
                            Tag = "FPS",
                            Title = "Call of Duty: Black Ops II"
                        },
                        new
                        {
                            Id = 6,
                            Rank = 6,
                            Tag = "RPG",
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 7,
                            Rank = 7,
                            Tag = "CRPG",
                            Title = "Baldur's Gate 3"
                        },
                        new
                        {
                            Id = 8,
                            Rank = 8,
                            Tag = "Action RPG",
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 9,
                            Rank = 9,
                            Tag = "Colony Sim",
                            Title = "RimWorld"
                        },
                        new
                        {
                            Id = 10,
                            Rank = 10,
                            Tag = "Platformer",
                            Title = "Psychonauts"
                        });
                });

            modelBuilder.Entity("VideoGamesSite.Models.Game", b =>
                {
                    b.HasOne("VideoGamesSite.Models.Platform", "Platform")
                        .WithMany("Games")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("VideoGamesSite.Models.Platform", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
